apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ilab-test03 
  description: Secure Supply Chain Example for InstructLab Application example to start contributing on LLMs   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:
    # ArgoCD apps from this template used rhtap-gitops as the grouping
    argocd/app-selector: rhtap/gitops=ilab-test03  
    janus-idp.io/tekton: ilab-test03 
    backstage.io/kubernetes-id: ilab-test03 
    backstage.io/techdocs-ref: dir:. 
    quay.io/repository-slug: tpetkos/ilab-test
  tags: ["ai", "instructlab", "python"] 
spec:
  type: service
  owner: user:guest 
  lifecycle: experimental
 